import type { ActionKind } from '../core/index.js';

/** Playwright `pw:api` step verbs (a title before any value or locator) → neutral kinds. */
export const ACTION_KINDS: Readonly<Record<string, ActionKind>> = {
  Navigate: 'navigate',
  Click: 'click',
  'Double click': 'doubleClick',
  Tap: 'tap',
  Hover: 'hover',
  Fill: 'fill',
  Type: 'type',
  Insert: 'type',
  Press: 'press',
  Check: 'check',
  Uncheck: 'uncheck',
  'Select option': 'select',
  'Set input files': 'upload',
  'Go back': 'goBack',
  'Go forward': 'goForward',
  Reload: 'reload',
  'Wait for timeout': 'wait',
  'Wait for selector': 'wait',
  'Wait for function': 'wait',
  'Wait for state': 'wait',
  'Wait for event': 'wait',
  'Wait for navigation': 'wait',
  'Wait for load state': 'wait',
  'Wait for URL': 'wait',
  Evaluate: 'script',
  'Add init script': 'script',
  'Add script tag': 'script',
  'Dispatch event': 'dispatch',
  Dispatch: 'dispatch',
  'Get text content': 'read',
  'Get inner text': 'read',
  'Get input value': 'read',
  'Get attribute': 'read',
  'Get HTML': 'read',
  'Get content': 'read',
  'Get page title': 'read',
  GET: 'request',
  POST: 'request',
  PUT: 'request',
  PATCH: 'request',
  DELETE: 'request',
  HEAD: 'request',
  'Launch browser': 'setup',
  'Create context': 'setup',
  'Create page': 'setup',
  'Close context': 'setup',
  'Close page': 'setup',
  'Close browser': 'setup',
};

/** Verbs older Playwright wrote differently (1.53–1.62 titles) → the verb above. */
export const VERB_ALIASES: Readonly<Record<string, string>> = {
  'Navigate to': 'Navigate',
};
